### PR TITLE
added myself

### PR DESCRIPTION
**Pull request by ag**

### CODE REVIEW

**Comment by Schemetrical** [comment]
Could you move yourself down to fit alphabetically, thanks :). I'm sure you had a good time last year at dubdub!

**Comment by ag** [comment]
Sure. Sorry but I didn't notice a alphabetical order ✌️

**Comment by ag** [comment]
better? @Schemetrical

**Comment by Schemetrical** [comment]
Gratz again!

**Comment by ag** [comment]
thanks 😍 one more thing: i noticed that many of 'us' have a website. shouldn't we also add a column for our websites? @Schemetrical

**Comment by Schemetrical** [comment]
It's to prevent abuse because we can't go around and check if every person's website rightfully is theirs. Even if I were to add it now, it would be too late to be meaningful. Maybe next year :)

**Pull request merged**
