### PR TITLE
Added Myself (John Harding)

### PR DESCRIPTION
**Pull request by JohnnyH1012**
Added myself with initial commit, fixed typo with second.

### CODE REVIEW

**Comment by Schemetrical** [comment]
Please add an extra pipe, thanks.

**Comment by JohnnyH1012** [comment]
Any reason I wasn't added?

**Comment by Schemetrical** [comment]
You were missing a trailing pipe and I didn't have a computer to add the pipe for you (on mobile).

**Comment by Schemetrical** [comment]
Sorry, I just saw the pipe, in we go :-)

**Comment by Schemetrical** [comment]
Sorry about that, mobile Github was a bit of a pain and didn't show the commits. I was gone for the weekend and only had mobile.

**Comment by JohnnyH1012** [comment]
It's okay, I'm sorry- I had no idea you were on mobile. Thank you!

**Pull request merged**
