### PR TITLE
added myself

### PR DESCRIPTION
**Pull request by guidev**

### CODE REVIEW

**Comment by Schemetrical** [comment]
Is your Twitter compromised?

**Comment by guidev** [comment]
nope

**Comment by Schemetrical** [comment]
We cannot add a twitter account that is solely comprised of advertisements then. Sorry, you can let me know if you have deleted those ad tweets (because I'm sure you didn't intend them to be there).

**Comment by guidev** [comment]
ok, I took care of them. apparently some apps were tweeting on my behalf

**Comment by Schemetrical** [comment]
Congrats!

**Pull request merged**
